# Thymeleaf Config
spring:
#  thymeleaf:
#    prefix: classpath:dist/

# DataSource MainConfig
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://a.gamehu4399.top:13306/arcloud?
    username: testuser
    password: testpassword
#File

  servlet:
    multipart:
      max-file-size: 1501921000
      max-request-size: 1501921000

# Logger MainConfig
logging:
  level:
    com.anaple.pure_web_server: debug