# Thymeleaf Config
spring:
  thymeleaf:
    prefix: classpath:dist/

# DataSource MainConfig
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.181.51:3307/arcloud?
    username: test1
    password: passwdtest1
#File

  servlet:
    multipart:
      max-file-size: 150192100
      max-request-size: 150192100

# Logger MainConfig
logging:
  level:
    com.anaple.pure_web_server: debug